# tasks file for snapd role
---
- name: ensure that EPEL package is installed
  become: true
  package:
    name: epel-release
    state: present
    update_cache: true
  when: 'ansible_distribution == "CentOS"'
  tags: snap, snap-install

- name: install snapd package
  become: true
  package:
    name: snapd
    state: present
    update_cache: true
    enablerepo: "{{ (ansible_distribution == 'CentOS') | ternary('epel', omit) }}"
  tags: snap, snap-install

- name: enable snapd socket
  become: true
  service:
    name: snapd.socket
    state: started
    enabled: true
  tags: snap, snap-socket

- name: enable classic snap support on RedHat systems
  become: true
  file:
    path: /snap
    src: /var/lib/snapd/snap
    state: link
  when: "ansible_os_family == 'RedHat'"
  tags: snap, snap-install

- name: install packages from snap
  become: true
  snap:
    name: "{{ item.name | default(item) }}"
    channel: "{{ item.channel | default('stable') }}"
    classic: "{{ item.classic | default(false) }}"
  loop: "{{ snap_packages }}"
  when: snap_packages is defined
  tags: snap, snap-packages
