---
dependency:
  name: galaxy
  enabled: false
driver:
  name: delegated
lint: |
  set -e
  yamllint .
  ansible-lint -p .
platforms:
  - name: instance
    source:
      alias: "${MOLECULE_DISTRO:-ubuntu/18.04}"
provisioner:
  name: ansible
  connection_options:
    ansible_connection: lxd
  playbooks:
    create: ../resources/lxd/create.yml
    prepare: ../resources/lxd/prepare.yml
    destroy: ../resources/lxd/destroy.yml
verifier:
  name: ansible
