name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  molecule:
    name: Test on ${{ matrix.distro }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        distro:
          - ubuntu/20.04
          - ubuntu/18.04
          - debian/10
          - fedora/32
          - fedora/31
          - centos/7
          - centos/8

    steps:
      - name: Checks-out repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: sudo python3 -m pip install --quiet ansible-lint molecule yamllint

      - name: Get latest yamllint config
        run: curl -sSo .yamllint https://raw.githubusercontent.com/ansible/galaxy/master/galaxy/importer/linters/yamllint.yaml

      - name: Initialize LXD
        run: |
          sudo chmod o+g /var/snap/lxd/common/lxd/unix.socket
          lxd init --auto

      - name: Run Molecule tests
        run: molecule test
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: true
