name: Import to Galaxy

on:
  workflow_run:
    workflows: ["CI"]
    # branches: [main]
    types:
      - completed

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - name: Import role to ansible galaxy
        run: ansible-galaxy role import --api-key ${{ secrets.GALAXY_TOKEN }} ${{ github.repository_owner }} ${{ github.event.repository.name }}
