---
name: Molecule

on:
  push:
    branches:
      - '*'
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  molecule:
    name: Test on ${{ matrix.distro }}
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: bonddim.snapd
    strategy:
      matrix:
        distro:
          - ubuntu/20.04
          - ubuntu/18.04
          - debian/10
          - fedora/32
          - fedora/33
          - centos/7
          - centos/8

    steps:
      - name: Checks-out repository
        uses: actions/checkout@v2
        with:
          path: bonddim.snapd

      - name: LXD init
        uses: bonddim/action-lxd@v1

      - name: Install dependencies
        run: sudo python3 -m pip install ansible-lint yamllint molecule-lxd

      - name: Get latest yamllint config
        run: curl -sSo .yamllint https://raw.githubusercontent.com/ansible/galaxy/master/galaxy/importer/linters/yamllint.yaml

      - name: Run Molecule tests
        run: molecule test
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: true
