---
name: Molecule

on:
  push:
    branches:
      - '**'
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  molecule:
    # skip job on pull requests from base repository
    if: github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - ansible<2.10
        distro:
          - ubuntu/20.04
          - ubuntu/18.04
          - debian/10
          - fedora/32
          - fedora/33
          - centos/7
          - centos/8
        include:
          - ansible: ansible>=2.10
            distro: ubuntu/20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: bonddim/action-lxd-init@stable
      - name: Install dependencies
        run: python3 -m pip install --no-cache-dir --requirement .github/workflows/requirements.txt '${{ matrix.ansible }}'
      - run: molecule test
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: true
